### ISSUE TITLE
Too Long time to do KS test on  one data set

### ISSUE THREAD

**Issue by WeiFoo** [ai-se/HDP#10]
During the past day, when I got a source data set with 36 rows, target with 200 rows, the apache.commons.math KS test run on it more than 6 hours, and still no results returned for that case.

The reason may be some low level java issues and I have no idea of that up to now.

**Comment by WeiFoo** [comment]
To continue with my experiment, I mean I don't want to wait for that long time to do KS test. I try using the KS test in **scipy**.

Baseline: I will run JC's experiment with KS test form **scipy**, the results will be used as my baseline
Comparison: 
- small source with small target data set  to do KS test using **scipy**
- large source with small target data set  to do KS test using  **scipy**

Expectation:
  the results from comparison group will have similar or even better results than baseline results.

**Comment by timm** [comment]
suggestion: If you take X% of the data (X<100%, X \in {50,100,200,400, 600...} samples selected at random) how inaccurate are your KS values?

**Comment by WeiFoo** [comment]
We can only compare it with the baseline. but it's been running more than 12 hours, and haven't done yet.

**Comment by timm** [comment]
huh, like i say, stochastic sample?

**Comment by WeiFoo** [comment]
yes, time is spent on KS test and defect prediction.
now with stochastic sample, we spend less time on KS test but the remaining tasks still the same.
