### ISSUE TITLE
ReliefAttributeSelection

### ISSUE THREAD

**Issue by WeiFoo** [ai-se/HDP#3]

**Comment by WeiFoo** [comment]
with default settings: no setting actually! 

./dataset/SOFTLAB/ar1.arff ===> 0.464
./dataset/SOFTLAB/ar3.arff ===> 0.833
./dataset/SOFTLAB/ar4.arff ===> 0.812
./dataset/SOFTLAB/ar5.arff ===> 0.938
./dataset/SOFTLAB/ar6.arff ===> 0.282
./dataset/NASA/cm1.arff ===> 0.285
./dataset/NASA/mw1.arff ===> 0.268
./dataset/NASA/PC1.arff ===> 0.696
./dataset/NASA/PC3.arff ===> 0.228
./dataset/NASA/PC4.arff ===> 0.287
./dataset/AEEEM/EQ.arff ===> 0.202
./dataset/AEEEM/JDT.arff ===> 0.765
./dataset/AEEEM/LC.arff ===> 0.64
./dataset/AEEEM/ML.arff ===> 0.397
./dataset/AEEEM/PDE.arff ===> 0.498
./dataset/Relink/apache.arff ===> 0.324
./dataset/Relink/safe.arff ===> 0.688
./dataset/Relink/zxing.arff ===> 0.34
./dataset/MORPH/ant-1.3.arff ===> 0.824
./dataset/MORPH/arc.arff ===> 0.761
./dataset/MORPH/camel-1.0.arff ===> 0.664
./dataset/MORPH/poi-1.5.arff ===> 0.744
./dataset/MORPH/redktor.arff ===> 0.582
./dataset/MORPH/skarbonka.arff ===> 0.511
./dataset/MORPH/tomcat.arff ===> 0.183
./dataset/MORPH/velocity-1.4.arff ===> 0.423
./dataset/MORPH/xalan-2.4.arff ===> 0.626
./dataset/MORPH/xerces-1.2.arff ===> 0.614

**Comment by WeiFoo** [comment]
with default settings in weka: options=["-M","-1","-D","1","-K","10"])
./dataset/SOFTLAB/ar1.arff ===> 0.464
./dataset/SOFTLAB/ar3.arff ===> 0.833
./dataset/SOFTLAB/ar4.arff ===> 0.812
./dataset/SOFTLAB/ar5.arff ===> 0.938
./dataset/SOFTLAB/ar6.arff ===> 0.282
./dataset/NASA/cm1.arff ===> 0.285
./dataset/NASA/mw1.arff ===> 0.268
./dataset/NASA/PC1.arff ===> 0.696
./dataset/NASA/PC3.arff ===> 0.228
./dataset/NASA/PC4.arff ===> 0.287
./dataset/AEEEM/EQ.arff ===> 0.202
./dataset/AEEEM/JDT.arff ===> 0.765
./dataset/AEEEM/LC.arff ===> 0.64
./dataset/AEEEM/ML.arff ===> 0.397
./dataset/AEEEM/PDE.arff ===> 0.498
./dataset/Relink/apache.arff ===> 0.324
./dataset/Relink/safe.arff ===> 0.688
./dataset/Relink/zxing.arff ===> 0.34
./dataset/MORPH/ant-1.3.arff ===> 0.824
./dataset/MORPH/arc.arff ===> 0.761
./dataset/MORPH/camel-1.0.arff ===> 0.664
./dataset/MORPH/poi-1.5.arff ===> 0.744
./dataset/MORPH/redktor.arff ===> 0.582
./dataset/MORPH/skarbonka.arff ===> 0.511
./dataset/MORPH/tomcat.arff ===> 0.183
./dataset/MORPH/velocity-1.4.arff ===> 0.423
./dataset/MORPH/xalan-2.4.arff ===> 0.626
./dataset/MORPH/xerces-1.2.arff ===> 0.614

They're the same actually!

**Comment by timm** [comment]
so relief sucks, right?

t

On Thu, Jun 25, 2015 at 3:57 PM, Wei Fu notifications@github.com wrote:

> with default settings: no setting actually!
> 
> ./dataset/SOFTLAB/ar1.arff ===> 0.464
> ./dataset/SOFTLAB/ar3.arff ===> 0.833
> ./dataset/SOFTLAB/ar4.arff ===> 0.812
> ./dataset/SOFTLAB/ar5.arff ===> 0.938
> ./dataset/SOFTLAB/ar6.arff ===> 0.282
> ./dataset/NASA/cm1.arff ===> 0.285
> ./dataset/NASA/mw1.arff ===> 0.268
> ./dataset/NASA/PC1.arff ===> 0.696
> ./dataset/NASA/PC3.arff ===> 0.228
> ./dataset/NASA/PC4.arff ===> 0.287
> ./dataset/AEEEM/EQ.arff ===> 0.202
> ./dataset/AEEEM/JDT.arff ===> 0.765
> ./dataset/AEEEM/LC.arff ===> 0.64
> ./dataset/AEEEM/ML.arff ===> 0.397
> ./dataset/AEEEM/PDE.arff ===> 0.498
> ./dataset/Relink/apache.arff ===> 0.324
> ./dataset/Relink/safe.arff ===> 0.688
> ./dataset/Relink/zxing.arff ===> 0.34
> ./dataset/MORPH/ant-1.3.arff ===> 0.824
> ./dataset/MORPH/arc.arff ===> 0.761
> ./dataset/MORPH/camel-1.0.arff ===> 0.664
> ./dataset/MORPH/poi-1.5.arff ===> 0.744
> ./dataset/MORPH/redktor.arff ===> 0.582
> ./dataset/MORPH/skarbonka.arff ===> 0.511
> ./dataset/MORPH/tomcat.arff ===> 0.183
> ./dataset/MORPH/velocity-1.4.arff ===> 0.423
> ./dataset/MORPH/xalan-2.4.arff ===> 0.626
> ./dataset/MORPH/xerces-1.2.arff ===> 0.614
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ai-se/HDP/issues/3#issuecomment-115376996.

## 

:: there are some who call me...   timm (tim menzies)
:: (prof :of   '(SE AI)  :at '(comSci ncstate nc usa sol virgo all nil)
::     :cell   "+1-304-376-2859"
::     :skype 'menzies.tim
::     :home   "http://menzies.us")
::
:: Why search-based SE? Cause if you don't search, you won't find a thing.
:: "Engineering is optimization and optimization is search."
::
:: Note: I read email _ONCE_ a day in the evening (so no same day response).
